wordpress Mash.new unless attribute?("wordpress")
wordpress[:database_name] = "blog" unless wordpress.has_key?(:database_name)
wordpress[:database_user] = "blog" unless wordpress.has_key?(:database_user)
wordpress[:database_password] = "blog" unless wordpress.has_key?(:database_password)
wordpress[:database_host] = "localhost" unless wordpress.has_key?(:database_host)
