jira_subdomain "tickets" unless attribute?("jira_subdomain")
jira_virtual_host_name "#{jira_subdomain}.#{openaustralia[:domain]}" unless attribute?("jira_virtual_host_name")
# type-version-standalone
jira_version "enterprise-4.0.1" unless attribute?("jira_version")
jira_install_path "/www/#{jira_subdomain}" unless attribute?("jira_install_path")
jira_home "#{jira_install_path}/data" unless attribute?("jira_home")
jira_database "mysql" unless attribute?("jira_database")
jira_database_name "jira4db" unless attribute?("jira_database_name")
jira_database_host "localhost" unless attribute?("jira_database_host")
jira_database_user "jira" unless attribute?("jira_database_user")
jira_database_password "jira" unless attribute?("jira_database_password")
jira_run_user "www" unless attribute?("jira_run_user")
jira_timezone "AU" unless attribute?("jira_timezone")
jira_mem_initsize "128" unless attribute?("jira_mem_initsize")
jira_mem_maxsize "384" unless attribute?("jira_mem_maxsize")
